# -*- coding: utf-8 -*-
"""Contenu du site BEN WEB — une seule source de vérité pour les 11 pages."""

SITE = {
    "brand": "BEN WEB",
    "baseline": "Freelance Digital & IA",
    "domain": "https://ben-web.com",
    "email": "contact@ben-web.com",
    "whatsapp_display": "+66 97 049 9155",
    "whatsapp_link": "https://wa.me/66970499155",
    "instagram": "https://www.instagram.com/benweb",
    "tiktok": "https://www.tiktok.com/@benweb",
    "handle": "@benweb",
}

ICONS = {
    "nfc": '<path d="M4 8V6a2 2 0 0 1 2-2h2M16 4h2a2 2 0 0 1 2 2v2M20 16v2a2 2 0 0 1-2 2h-2M8 20H6a2 2 0 0 1-2-2v-2"/><path d="M9 9.5a4 4 0 0 1 0 5M12.5 7a7 7 0 0 1 0 10"/>',
    "resto": '<path d="M5 3v8a3 3 0 0 0 6 0V3M8 11v10M16 3c-1.5 2-2 4-2 6s.5 3 2 3 2-1 2-3-.5-4-2-6zM16 12v9"/>',
    "marketing": '<path d="M3 11v3a1 1 0 0 0 1 1h3l5 4V6L7 10H4a1 1 0 0 0-1 1z"/><path d="M17 8a5 5 0 0 1 0 8"/>',
    "site": '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M7 6.5h.01M10 6.5h.01"/>',
    "app": '<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M11 18.5h2"/>',
    "ecv": '<path d="M6 2h8l4 4v16H6z"/><path d="M14 2v4h4M9 12h6M9 16h4"/>',
    "audit": '<circle cx="11" cy="11" r="7"/><path d="m20 20-3.6-3.6"/><path d="M8.5 12.5v-2M11 13V9M13.5 12.5v-3"/>',
    "closing": '<path d="M4 5h16v11H9l-5 4z"/><path d="m9 10.5 2 2 4-4"/>',
    "ia": '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',
}

# --------------------------------------------------------------------------
# Réalisations réutilisables (toutes réelles — aucune invention)
# --------------------------------------------------------------------------
CASES = {
    "meen": {
        "img": "assets/work/meen.webp",
        "alt": "Page d'accueil de la boutique Meen : hero produit et bandeau de réassurance",
        "frame": "meen · boutique en ligne",
        "tags": ["E-commerce", "Shopify", "Automatisation Python"],
        "title": "Meen, boutique beauté et contenu SEO automatisé",
        "sub": "Marque de soin capillaire : boutique en ligne complète, du thème sur mesure jusqu'à la production de contenu.",
        "problem": "Lancer une boutique crédible autour d'un produit unique, avec un tunnel d'achat clair et suffisamment de contenu pour exister sur Google, sans équipe marketing derrière.",
        "solution": "Un thème Shopify retravaillé (page produit orientée conversion, réassurance, pages légales complètes) puis une couche d'automatisation en Python : déploiement du thème, des produits, de la navigation et des redirections via l'API Admin Shopify, et génération/publication d'articles de blog SEO en série.",
        "features": [
            "Page produit conçue pour la conversion (offre, réassurance, garanties)",
            "6 articles de blog SEO créés et publiés automatiquement par script",
            "Déploiement du thème, du catalogue et des menus en une commande",
            "Pages légales, cookies et CGV structurées pour la vente en ligne",
        ],
        "stack": ["Shopify / Liquid", "HTML · CSS · JS", "Python", "API Admin Shopify", "OAuth", "SEO"],
        "status": "Projet client",
        "note": "Boutique privée. Démonstration détaillée disponible en visio.",
    },
    "mdc": {
        "cover": {
            "eyebrow": "Application web complète",
            "title": "Du questionnaire client<br>à la livraison du site,<br><em>en un seul flux.</em>",
            "nodes": [("Questionnaire", "Brief guidé"), ("Commande", "Panier & paiement"),
                      ("Espace client", "Validation & fichiers"), ("Back-office", "Suivi & messages")],
            "foot": ("Next.js 14 · TypeScript · Tailwind", "19 routes API"),
        },
        "frame": "my digital career · plateforme",
        "tags": ["Application web", "Next.js", "Espace client & admin"],
        "title": "My Digital Career, plateforme de production de sites",
        "sub": "Projet entrepreneurial : industrialiser la création de sites, de la prise de brief à la livraison.",
        "problem": "Vendre un service digital sans passer ses journées en allers-retours par mail : il fallait un parcours où le client commande, dépose ses informations, valide sa maquette et récupère ses fichiers tout seul.",
        "solution": "Une application Next.js complète : site public animé, questionnaire de brief, panier et commande, espace client authentifié (suivi, validation, téléchargements), back-office administrateur (tableau de bord, statuts, messages, devis pro) et persistance branchée sur Google Sheets / Drive plutôt que sur une infrastructure coûteuse.",
        "features": [
            "Authentification par jetons JWT (jose) et mots de passe hachés (bcrypt)",
            "Espace client : suivi de commande, validation, téléchargement des livrables",
            "Back-office : tableau de bord, statuts, messagerie, devis professionnels",
            "Webhook de paiement, consentement cookies et suivi d'événements",
            "Interface multilingue et animations Framer Motion",
        ],
        "stack": ["Next.js 14", "TypeScript", "Tailwind CSS", "Framer Motion", "Google APIs", "JWT · bcrypt"],
        "status": "Projet entrepreneurial",
        "note": "Application privée (données clients). Visite guidée du back-office sur demande.",
    },
    "resto": {
        "cover": {
            "eyebrow": "Site multilingue · 5 langues",
            "title": "Une carte, cinq langues,<br>et les commandes<br><em>qui arrivent seules.</em>",
            "nodes": [("FR · EN", "Clientèle locale"), ("TR · TH · ZH", "Clientèle internationale"),
                      ("Carte dynamique", "Entrées → desserts"), ("Commandes", "Envoyées en cuisine")],
            "foot": ("Next.js 16 · React 19 · Tailwind", "Routing i18n"),
        },
        "frame": "restaurant · carte & commandes",
        "tags": ["Site & outil métier", "Multilingue", "Prise de commande"],
        "title": "Restaurant turc à Bangkok : carte multilingue et commandes",
        "sub": "Un restaurant dont les clients parlent cinq langues et dont les commandes arrivaient par messages éparpillés.",
        "problem": "Présenter une carte complète à une clientèle internationale, et centraliser les commandes sans imposer au restaurateur un logiciel de caisse coûteux.",
        "solution": "Un site Next.js avec routage par langue (français, anglais, turc, thaï, chinois), une carte structurée par catégories avec visuels et prix, un espace compte, une interface d'administration et des commandes envoyées automatiquement vers un tableau que le restaurant consulte depuis son téléphone.",
        "features": [
            "5 langues gérées par un dictionnaire typé, sans dépendance externe",
            "Carte dynamique : entrées, plats, desserts, boissons, prix à jour",
            "Commandes enregistrées automatiquement, consultables en salle",
            "Pages « nous connaître », mentions légales et espace administrateur",
        ],
        "stack": ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Google Sheets API"],
        "status": "Projet client",
        "note": "Site privé avant ouverture. Démonstration en visio possible.",
    },
    "ecv": {
        "img": "assets/work/manon.webp",
        "alt": "Site vitrine éditorial : grande typographie, portrait et navigation claire",
        "gallery": [
            ("assets/work/remi.webp", "Site vitrine sombre à accents dorés"),
            ("assets/work/miguel.webp", "Site vitrine bleu nuit avec badges de compétences"),
            ("assets/work/benjamin-ecv.webp", "Site vitrine clair bilingue français / anglais"),
        ],
        "frame": "collection · sites vitrines personnels",
        "tags": ["Sites vitrines", "5 sites", "Identités distinctes"],
        "title": "Collection de sites vitrines personnels",
        "sub": "Cinq sites, cinq univers graphiques : chaque personne devait avoir une présence en ligne qui lui ressemble, pas un template dupliqué.",
        "problem": "Un CV PDF ne dit rien de quelqu'un. L'objectif : un site que l'on envoie en un lien, qui donne une bonne impression en trois secondes et qui reste lisible sur mobile.",
        "solution": "Une direction artistique différente par profil (éditorial crème, bleu nuit, vert forêt/doré…), une structure commune éprouvée (hero, parcours, compétences, contact) et, pour certains, une version bilingue FR/EN ainsi qu'un CV PDF optimisé ATS généré par script Python.",
        "features": [
            "Direction artistique et copy sur mesure pour chaque profil",
            "Bilingue FR/EN avec bascule instantanée sur plusieurs versions",
            "CV PDF au format ATS généré automatiquement depuis le contenu du site",
            "HTML sémantique, méta SEO, temps de chargement quasi instantané",
        ],
        "stack": ["HTML sémantique", "CSS moderne", "JavaScript vanilla", "Python (PDF)", "Netlify"],
        "links": [("https://manon-moinse.netlify.app/", "Voir un site en ligne"),
                  ("https://remi-pavol.netlify.app/", "Voir un second exemple")],
    },
    "artiste": {
        "img": "assets/work/azzeddine.webp",
        "alt": "Site d'artiste sombre et doré : prochaines dates et accès rapide",
        "frame": "site artiste · événements & médias",
        "tags": ["Site artiste", "Médias & 3D", "Booking"],
        "title": "Site d'artiste : agenda, médias et page de liens",
        "sub": "Une présence en ligne pour un artiste-musicien : dates, univers visuel, extraits audio et vidéo, contact booking.",
        "problem": "Remplacer un simple compte Instagram par un point d'entrée professionnel : retrouver les dates, écouter, regarder, et surtout pouvoir réserver une date.",
        "solution": "Un site sombre et doré au rythme éditorial marqué : agenda et fiches événement, page de liens centralisant les réseaux et plateformes d'écoute, intégration de vidéos, d'extraits audio et d'un modèle 3D, carrousel d'instruments et formulaire de booking.",
        "features": [
            "Agenda et pages événement dédiées",
            "Page « links » unique pour Instagram, TikTok, Spotify, SoundCloud",
            "Intégration vidéo, audio et modèle 3D (.glb)",
            "Carrousel infini animé, contact WhatsApp direct",
        ],
        "stack": ["HTML · CSS · JS", "Animations sur mesure", "Médias embarqués", "3D (model-viewer)"],
        "status": "Projet de démonstration",
        "note": "Les dates affichées sur ce site sont des exemples, en attendant les annonces officielles.",
    },
    "carte": {
        "img": "assets/work/carte-visite.webp",
        "alt": "Carte de visite digitale interactive avec coordonnées et liens directs",
        "frame": "carte de visite digitale",
        "tags": ["Carte digitale", "Mobile-first", "Partage instantané"],
        "title": "Carte de visite digitale interactive",
        "sub": "Une page unique que l'on partage par lien, par QR code, ou d'un simple contact NFC.",
        "problem": "Après une rencontre professionnelle, tout se joue dans les minutes qui suivent. Une carte papier se perd ; un lien reste dans la conversation.",
        "solution": "Une carte animée en une page : identité, message court, coordonnées cliquables et boutons directs vers WhatsApp, LINE, LinkedIn et l'e-mail. Chargement immédiat, lisible en une main, et prête à être diffusée par QR code ou puce NFC.",
        "features": [
            "Animation d'ouverture et effet de profondeur maîtrisé",
            "Actions directes : appel, e-mail, WhatsApp, LINE, LinkedIn",
            "Conçue pour être diffusée par lien court, QR code ou NFC",
            "Poids minimal, aucun framework, hébergement gratuit",
        ],
        "stack": ["HTML · CSS · JS", "Design mobile-first", "QR / NFC"],
        "status": "Réalisé en une journée",
        "note": "Format idéal pour tester une identité avant un site complet.",
    },
}


# --------------------------------------------------------------------------
# Les 6 services, une page chacun
# --------------------------------------------------------------------------
SERVICES = [
    {
        "slug": "applications",
        "num": "01",
        "featured": True,
        "nav": "Applications web & mobile",
        "icon": "app",
        "thumb": "assets/work/mockup-application.webp",
        "thumb_alt": "Maquette d'interface : tableau de bord métier sur ordinateur et sur téléphone",
        "hub_line": "Outils métier, tableaux de bord, espaces clients et back-offices sur mesure.",
        "meta_title": "Création d'applications web & mobile : outils métier, dashboards, SaaS",
        "meta_desc": "Applications web sur mesure, installables sur mobile : outils métier, tableaux de bord, espaces clients, back-offices et MVP SaaS.",
        "h1": "Applications<br><em>web & mobile</em>",
        "lead": "Quand le tableur ne suit plus, qu'on se transmet des informations par capture d'écran et que chaque fin de mois demande trois heures de recopie : c'est le moment de passer à un outil qui travaille pour vous.",
        "chips": ["Installable sur mobile (PWA)", "Espaces client & admin", "Connecté à vos outils"],
        "problem": "Les logiciels du marché sont soit trop chers, soit trop larges : vous payez chaque mois pour quarante fonctions dont vous en utilisez trois, et jamais celles dont vous avez vraiment besoin. Alors tout finit dans un tableur partagé que personne ne maîtrise vraiment.",
        "solution": "Je construis l'outil qui correspond exactement à votre façon de travailler : vos étapes, votre vocabulaire, vos règles. Accessible depuis un navigateur, installable sur le téléphone comme une application, connecté à ce que vous utilisez déjà, et sans abonnement mensuel imposé.",
        "includes": [
            ("Outil métier sur mesure", "Vos processus, vos statuts, vos droits d'accès. Rien de superflu."),
            ("Tableaux de bord", "Les chiffres qui pilotent l'activité, à jour, lisibles sur téléphone."),
            ("Espace client", "Vos clients suivent, valident et téléchargent en autonomie. Moins d'allers-retours."),
            ("Back-office", "Une interface d'administration claire pour vos équipes, pas une base de données brute."),
            ("Installable sur mobile", "Application web progressive : icône sur l'écran d'accueil, sans passer par les stores."),
            ("Intégrations", "Google Sheets, Drive, paiement, e-mail, API tierces : vos outils existants restent utiles."),
        ],
        "cases": ["mdc"],
        "note": "Je développe des applications web, installables sur mobile (PWA). Pour une application native publiée sur l'App Store ou Google Play, je vous le dis franchement lors du cadrage plutôt que de vous vendre autre chose.",
    },
    {
        "slug": "sites-internet",
        "num": "02",
        "nav": "Création de sites internet",
        "icon": "site",
        "thumb": "assets/work/azzeddine.webp",
        "thumb_alt": "Site d'artiste sombre et doré",
        "hub_line": "Sites vitrines, landing pages, boutiques et refontes, conçus sur mesure, jamais sur template.",
        "meta_title": "Création de site internet sur mesure : vitrine, e-commerce, refonte",
        "meta_desc": "Sites vitrines, landing pages, boutiques en ligne et refontes. Design sur mesure, code propre, performance et SEO technique. Première version en 48–72 h.",
        "h1": "Création de<br><em>sites internet</em>",
        "lead": "Un site qui vous ressemble, qui charge instantanément et qui donne envie de vous écrire. Pas un template acheté et rempli à la hâte : une structure pensée pour votre activité et écrite à la main.",
        "chips": ["Première version en 48–72 h", "Code propre et à vous", "Responsive irréprochable"],
        "problem": "Deux impasses classiques : le site fait sur un constructeur en ligne, lent, générique et impossible à faire évoluer, ou le devis d'agence à plusieurs milliers d'euros avec trois mois de délai. Entre les deux, il n'y a souvent rien.",
        "solution": "Je conçois et développe votre site sur mesure, avec les outils modernes et un workflow assisté par IA qui supprime le temps mécanique. Vous obtenez un site rapide, propre, référençable et évolutif, livré en quelques jours. Et le code vous appartient entièrement.",
        "includes": [
            ("Site vitrine", "Présenter votre activité, vos offres et votre crédibilité, et déclencher le contact."),
            ("Landing page", "Une page unique pour une campagne, un produit ou une offre précise."),
            ("Boutique en ligne", "Catalogue, tunnel d'achat, paiement, pages légales. Prêt à vendre."),
            ("Refonte", "Repartir de l'existant : même contenu, meilleure structure, bien meilleure impression."),
            ("Multilingue", "Une version par langue, avec une vraie structure d'URL, pas une traduction automatique."),
            ("Hébergement & domaine", "Mise en ligne, nom de domaine, certificat, e-mails professionnels."),
        ],
        "universes": [
            {"id": "resto", "img": "assets/work/u-resto.webp", "nom": "Restaurant", "lieu": "Bangkok",
             "alt": "Maquette de site pour un restaurant : accroche éditoriale, réservation et version mobile"},
            {"id": "avocat", "img": "assets/work/u-avocat.webp", "nom": "Cabinet d'avocats", "lieu": "Lyon",
             "alt": "Maquette de site pour un cabinet d'avocats : domaines d'expertise et prise de rendez-vous"},
            {"id": "sport", "img": "assets/work/u-sport.webp", "nom": "Salle de sport", "lieu": "Paris",
             "alt": "Maquette de site pour une salle de sport : planning des cours et réservation"},
        ],
        "cases": ["meen", "artiste", "ecv"],
    },
    {
        "slug": "audit-marketing",
        "num": "03",
        "nav": "Audit & Marketing",
        "icon": "audit",
        "thumb": "assets/work/mockup-audit.webp",
        "thumb_alt": "Illustration : rapport d'audit classé par impact et indicateurs du site",
        "hub_line": "Ce qui cloche sur votre site existant, puis ce qui ramène vraiment des clients.",
        "meta_title": "Audit de site et marketing digital pour entreprises",
        "meta_desc": "Audit complet de votre site existant, performance, SEO, mobile et conversion, avec un rapport priorisé. Puis acquisition, landing pages et contenus.",
        "h1": "Audit<br><em>&amp; marketing</em>",
        "lead": "Avant de refaire quoi que ce soit, il faut savoir ce qui ne va pas. J'audite votre site existant, je vous rends les priorités classées par impact, puis je m'occupe de ce qui ramène des clients.",
        "chips": ["Rapport d'audit en 48 h", "Priorités classées par impact", "SEO, mobile, conversion"],
        "problem": "Beaucoup d'entreprises paient pour une visibilité qu'elles ne mesurent pas. Le site est lent, invisible sur Google, illisible sur téléphone, et personne ne sait vraiment pourquoi les visiteurs repartent sans écrire. Refaire le site en entier coûte cher et ne règle pas toujours le vrai problème.",
        "solution": "Je commence par regarder ce que vous avez déjà : vitesse, structure, référencement, parcours mobile, clarté du message. Vous recevez un rapport classé par impact et par effort, assez précis pour être exécuté par n'importe qui. Ensuite, si vous le souhaitez, je m'occupe des corrections et de tout ce qui ramène du trafic utile.",
        "includes_groups": [
            ("Auditer l'existant", [
                ("Performance", "Temps de chargement, poids des pages, ce qui fait fuir un visiteur avant même de lire."),
                ("SEO technique", "Indexation, structure des titres, métadonnées, données structurées, sitemap."),
                ("Parcours et conversion", "Où le visiteur s'arrête, ce qui manque pour qu'il vous écrive ou qu'il achète."),
                ("Expérience mobile", "Lisibilité, zones tactiles, chargement. C'est ce que voit la majorité de votre trafic."),
                ("Contenus", "Ce que dit votre site, ce qu'il oublie de dire, et ce que cherchent réellement vos clients."),
                ("Rapport priorisé", "Une liste classée par impact et par effort, utilisable telle quelle, même sans moi."),
            ]),
            ("Attirer et convertir", [
                ("Landing pages qui convertissent", "Une page, un objectif, une action. Message, preuve, réassurance, appel à l'action."),
                ("SEO technique", "Structure sémantique, métadonnées, vitesse, données structurées, sitemap."),
                ("SEO de contenu", "Articles utiles positionnés sur les recherches de vos clients. Production accélérée par l'IA."),
                ("Contenus et visuels", "Textes, images et assets digitaux cohérents avec votre identité."),
                ("Optimisation de conversion", "Analyse des points de fuite, tests, ajustements sur les pages qui comptent."),
                ("Mesure", "Analytics et suivi des événements : vous savez ce qui ramène des clients, pas seulement des clics."),
            ]),
        ],
        "cases": ["meen"],
        "note": "L'audit se facture au forfait, annoncé avant de commencer. Il reste utile même si vous confiez ensuite les corrections à quelqu'un d'autre : le rapport est écrit pour être exécutable par n'importe quel prestataire.",
    },
    {
        "slug": "cartes-restaurant",
        "num": "04",
        "nav": "Cartes restaurant connectées",
        "icon": "resto",
        "thumb": "assets/work/mockup-restaurant.webp",
        "thumb_alt": "Maquette d'interface : carte sur téléphone, écran cuisine et tableau de bord",
        "hub_line": "Carte QR multilingue, commandes envoyées directement en cuisine, suivi client et tableau de bord.",
        "meta_title": "Carte de restaurant connectée : commandes en cuisine & suivi",
        "meta_desc": "Carte digitale multilingue par QR code : le client commande depuis sa table, la commande part directement en cuisine, avec suivi, paiement en ligne et tableau de bord.",
        "h1": "Cartes restaurant<br><em>connectées</em>",
        "lead": "Le client scanne le QR posé sur la table. La carte s'ouvre dans sa langue, avec les photos et les prix à jour. Il commande depuis son téléphone : la commande s'affiche immédiatement en cuisine, et il suit son avancement sans avoir à chercher un serveur du regard.",
        "chips": ["Sans commission par commande", "Carte modifiable en 10 secondes", "Multilingue"],
        "problem": "Une carte imprimée est périmée dès qu'un prix bouge ou qu'un plat manque. Les plateformes de commande prennent une commission sur chaque ticket. Et en salle, le temps passé à prendre les commandes est du temps qui n'est pas passé à servir, surtout quand la clientèle est internationale et que la barrière de la langue ralentit tout.",
        "solution": "Un site de commande à votre nom, sans intermédiaire et sans commission. La carte est multilingue et se met à jour en quelques secondes depuis votre téléphone. Les commandes arrivent directement sur l'écran de la cuisine, horodatées et numérotées par table. Le client suit son statut, paie en ligne s'il le souhaite, et vous récupérez les chiffres qui comptent dans un tableau de bord.",
        "includes": [
            ("Carte digitale multilingue", "Catégories, photos, prix, allergènes, plats du jour, à jour en permanence."),
            ("Commande depuis la table", "QR code par table : le numéro de table part avec la commande, sans erreur."),
            ("Affichage cuisine", "Les commandes s'affichent en temps réel sur une tablette ou un écran, par ordre d'arrivée."),
            ("Suivi côté client", "Reçue → en préparation → prête. Moins d'attente ressentie, moins de relances en salle."),
            ("Paiement en ligne (option)", "Encaissement à la commande ou à la fin du repas, selon votre fonctionnement."),
            ("Tableau de bord & KPI", "Plats les plus vendus, panier moyen, heures de pointe, chiffre par service."),
        ],
        "cases": ["resto"],
        "note": "Le paiement en ligne dépend d'un prestataire d'encaissement (Stripe ou équivalent) : je réalise l'intégration, les frais de transaction restent ceux du prestataire.",
    },
    {
        "slug": "cartes-nfc",
        "num": "05",
        "nav": "Cartes digitales & NFC",
        "icon": "nfc",
        "thumb": "assets/work/carte-visite.webp",
        "thumb_alt": "Carte de visite digitale interactive",
        "hub_line": "Une carte physique NFC + une page de contact qui s'ouvre d'un simple contact avec le téléphone.",
        "meta_title": "Cartes de visite digitales & NFC pour commerciaux",
        "meta_desc": "Carte de visite digitale reliée à une puce NFC : votre prospect approche son téléphone, votre fiche s'ouvre et il vous enregistre en un geste. Livrée en 48 h.",
        "h1": "Cartes digitales &<br><em>NFC</em>",
        "lead": "Votre prospect approche son téléphone de votre carte. Votre fiche s'ouvre instantanément : photo, activité, boutons d'appel, WhatsApp, e-mail, LinkedIn. Il vous enregistre en un geste. Plus rien ne se perd au fond d'une poche.",
        "chips": ["Livrée en 48 h", "Commerciaux · indépendants · équipes", "Modifiable à distance"],
        "problem": "Une carte de visite papier coûte cher à réimprimer, se perd, et ne dit rien de plus que votre nom. Après un salon ou un rendez-vous, la moitié de vos contacts ne vous rappellent jamais, non pas parce qu'ils ne sont pas intéressés, mais parce qu'ils n'ont plus vos coordonnées sous la main.",
        "solution": "Je conçois votre page de contact digitale, rapide, élégante et à votre image, puis je l'encode sur une puce NFC. Un contact avec le téléphone ouvre la page. Pas d'application à installer, ni pour vous ni pour votre interlocuteur. Et quand votre numéro, votre poste ou votre offre change, je mets la page à jour : la carte physique, elle, ne bouge pas.",
        "includes": [
            ("Page de contact sur mesure", "Votre identité, votre photo, votre message en une phrase. Pas un template générique."),
            ("Actions en un clic", "Appeler, envoyer un WhatsApp, un e-mail, ouvrir LinkedIn, enregistrer le contact."),
            ("Fiche contact téléchargeable", "Un bouton ajoute vos coordonnées au répertoire du téléphone, avec votre photo."),
            ("Puce NFC + QR code", "La puce pour le geste rapide, le QR imprimé en secours pour les téléphones plus anciens."),
            ("Mise à jour à distance", "Un changement de numéro ou de poste ne coûte plus une réimpression."),
            ("Version équipe", "Une carte par commercial, une charte commune, une page d'entreprise centrale."),
        ],
        "cases": ["carte"],
        "note": "Je réalise la page, l'encodage NFC et le visuel de la carte. Les cartes physiques (PVC, métal, bois) sont commandées chez un imprimeur spécialisé. Je vous accompagne sur le choix et la quantité.",
    },
    {
        "slug": "ia-automatisation",
        "num": "06",
        "nav": "IA & automatisation",
        "icon": "ia",
        "thumb": "assets/work/mockup-automatisation.webp",
        "thumb_alt": "Maquette d'interface : flux d'automatisation et journal d'exécution",
        "hub_line": "Supprimer les tâches répétitives : scripts, intégrations IA et outils connectés entre eux.",
        "meta_title": "IA & automatisation : workflows, intégrations et assistants sur mesure",
        "meta_desc": "Automatisation des tâches répétitives, intégration de modèles IA, assistants et scripts métier. Objectif : du temps récupéré, pas de la technologie pour la technologie.",
        "h1": "IA &<br><em>automatisation</em>",
        "lead": "Chaque semaine, la même série de gestes : recopier, renommer, relancer, republier. Ce temps-là est récupérable. L'objectif n'est jamais la technologie, c'est le nombre d'heures que vous ne passerez plus dessus.",
        "chips": ["Gain de temps mesurable", "Connecté à vos outils", "Sans abonnement imposé"],
        "problem": "Les tâches répétitives ne se voient pas dans un bilan, mais elles coûtent : la saisie de commandes, la mise à jour d'un catalogue, la rédaction de fiches produits, les relances, les rapports mensuels. Ce sont souvent plusieurs heures par semaine, tous les mois de l'année.",
        "solution": "Je repère les tâches automatisables, puis je construis l'automatisation correspondante : un script, une intégration entre vos outils, ou un assistant connecté à un modèle IA. Vous gardez le contrôle et la validation ; la machine fait le travail mécanique.",
        "includes": [
            ("Automatisation de tâches", "Import, export, mise à jour, publication, relances : déclenchés seuls ou en un clic."),
            ("Intégration IA", "Génération et traitement de textes, tri, résumé, classification, extraction de données."),
            ("Assistant / chatbot", "Un assistant nourri de vos documents pour répondre à vos clients ou à vos équipes."),
            ("Génération de contenu", "Fiches produits, articles SEO, descriptions : produits en série et publiés automatiquement."),
            ("Connexion entre outils", "Site, tableur, Drive, e-mail, CRM, facturation : les données circulent enfin toutes seules."),
            ("Scripts métier", "Les opérations spécifiques à votre activité, celles qu'aucun logiciel du marché ne couvre."),
        ],
        "cases": ["meen", "mdc"],
    },
    {
        "slug": "closing",
        "num": "07",
        "nav": "Setting & Closing",
        "icon": "closing",
        "thumb": "assets/work/mockup-closing.webp",
        "thumb_alt": "Illustration : des leads entrants jusqu'à la vente conclue",
        "featured": True,
        "hub_line": "Vos leads traités, qualifiés et conclus : je réponds, je qualifie, je prends les rendez-vous et je closes.",
        "meta_title": "Setting et closing : traitement des leads et appels de vente",
        "meta_desc": "Réponse aux leads, qualification, prise de rendez-vous, appels de vente en visio, traitement des objections et relance. Commission sur les ventes ou forfait, sur devis.",
        "h1": "Setting<br><em>&amp; closing</em>",
        "lead": "Vous générez des leads, mais ils dorment dans vos messages privés. Les relances passent à la trappe, les rendez-vous ne se transforment pas. Je prends cette partie en charge, de la première réponse jusqu'à la vente conclue.",
        "chips": ["Commission ou forfait, sur devis", "Coachs, formateurs, agences, e-commerce, SaaS", "FR et EN"],
        "problem": "Un lead qui attend deux jours est un lead perdu. La plupart des indépendants et des petites structures répondent quand elles ont le temps, entre deux livraisons client. Résultat : des prospects tièdes, des rendez-vous non confirmés, des devis jamais relancés, et l'impression que la publicité ou le contenu ne rapportent rien. Le problème n'est presque jamais le volume de leads, c'est ce qu'on en fait dans les heures qui suivent.",
        "solution": "Je prends le relais sur toute la partie commerciale. Je réponds aux messages, je qualifie pour ne garder que les gens vraiment concernés, je pose les rendez-vous dans votre agenda et je les mène en visio jusqu'à la décision. Vous gardez votre produit et votre expertise, je m'occupe de la conversation qui mène à la vente. Tout est tracé, pour que vous sachiez précisément où en est chaque prospect.",
        "includes": [
            ("Réponse aux leads", "Messages privés Instagram, formulaires, WhatsApp. Une réponse rapide, écrite dans votre voix, jamais un copier-coller."),
            ("Qualification", "Besoin réel, budget, échéance, capacité de décision. Vous ne parlez qu'aux prospects qui ont une raison d'acheter."),
            ("Prise de rendez-vous", "Créneaux posés dans votre agenda, confirmation et rappel avant l'appel pour limiter les absences."),
            ("Appels de vente en visio", "Découverte, présentation de l'offre, cadrage du prix et de la suite. Menés en français ou en anglais."),
            ("Traitement des objections", "Prix, délai, hésitation, comparaison avec un concurrent. Les objections se préparent avant l'appel, pas pendant."),
            ("Suivi et relance", "Chaque prospect est suivi jusqu'à une réponse claire, oui ou non. Un point régulier vous dit ce qui bloque et sur quoi ajuster l'offre."),
        ],
        "cases": [],
        "note": "Rémunération à la commission sur les ventes ou au forfait, sur devis. Le périmètre se fixe au cadrage : volume de leads, plages horaires, outils utilisés et ce qui reste de votre côté. Les missions commerciales étant confidentielles, cette page ne présente pas d'étude de cas publique, contrairement aux autres services.",
    },
]
